# Generated by Django 5.1.4 on 2025-01-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
