# Generated by Django 5.1.4 on 2025-01-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alta', '0002_remove_usuario_apellido_remove_usuario_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
